const RUN_PROCCESS = {
  ADDRESS_IS_USE: 'ADDRESS_IS_USE',
  SUCCESS_RUN_STANDALONE: 'SUCCESS_RUN_STANDALONE',
  SUCCESS_RUN_CHROME: 'SUCCESS_RUN_CHROME',
  SUCCESS_RUN_GECKO: 'SUCCESS_RUN_GECKO',
  PROCESS_EXIT: 'PROCESS_EXIT',
  SUCCESS_RUN: 'SUCCESS_RUN',
  DRIVER_NOT_FOUND: 'DRIVER_NOT_FOUND',
  UNHANDLED_EXCEPTION: 'UNHANDLED_EXCEPTION'
}

module.exports = RUN_PROCCESS