const statuses = {
  SUCCESS: 0,
  INVALID_SESSION_ID: 6,
  ELEMENT_NOT_FOUND: 7,
  FRAME_NOT_FOUND: 8,
  COMMAND_NOT_FOUND: 9,
  STALE_ELEMENT_REFERENCE: 10,
  ELEMENT_NOT_VISIBLE: 11,
  INVALID_ELEMENT_STATE: 12,
  INVALID_SELECTOR: 32,
  XPATH_ERROR: 19,
  UNKNOWN_ERROR: 13,
}


module.exports = statuses